# Generated by Django 4.0.5 on 2023-01-10 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentials',
            name='site_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
