# Generated by Django 4.0.5 on 2023-01-10 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passapp', '0002_credentials_site_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentials',
            name='site_name',
            field=models.CharField(default='site', max_length=100),
            preserve_default=False,
        ),
    ]
